services:
  agent_service:
    build:
      context: .
      dockerfile: docker/Dockerfile.service
    ports:
      - "80:80"
    env_file:
      - .env
    develop:
      watch:
        - path: src/agents/
          action: sync+restart
          target: /app/agents/
        - path: src/db/
          action: sync+restart
          target: /app/db/
        - path: src/schema/
          action: sync+restart
          target: /app/schema/
        - path: src/service/
          action: sync+restart
          target: /app/service/

  streamlit_app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    ports:
      - "8501:8501"
    depends_on:
      - agent_service
    environment:
      - AGENT_URL=http://agent_service
    develop:
      watch:
        - path: src/client/
          action: sync+restart
          target: /app/client/
        - path: src/schema/
          action: sync+restart
          target: /app/schema/
        - path: src/streamlit_app.py
          action: sync+restart
          target: /app/streamlit_app.py

  pgvector:
    hostname: pgvector
    build:
      context: .
      dockerfile: docker/Dockerfile.pgvector
    restart: always
    environment:
      POSTGRES_DB: agent_db
      POSTGRES_USER: agent_db_user
      POSTGRES_PASSWORD: 4g3ntdbus3r
      POSTGRES_MAX_CONNECTIONS: 100
      POSTGRES_IDLE_IN_TRANSACTION_SESSION_TIMEOUT: 360000
      TZ: "America/Sao_Paulo"
    ports:
      - "5432:5432"
    entrypoint: >
      /bin/bash -c "
      echo 'export POSTGRES_USER=${AGENT_PGVECTOR_USER}' > /etc/custom_env_agent.sh &&
      echo 'export POSTGRES_PASSWORD=${AGENT_PGVECTOR_PWD}' >> /etc/custom_env_agent.sh &&
      echo 'export POSTGRES_DB=${AGENT_PGVECTOR_DB}' >> /etc/custom_env_agent.sh &&
      echo 'export TZ=America/Sao_Paulo' >> /etc/custom_env_agent.sh &&
      chmod +x /etc/custom_env_agent.sh &&
      pgvector-entrypoint.sh"
